### ISSUE TITLE
Whoopee Cushion Tooltip Missing, causes server crashes

### ISSUE THREAD

**Issue by GentlemanGnu** [ochotonida/artifacts#123]
**Describe the bug**
On the server, when Players hover over the Whoopee Cushion within an inventory, the game freezes, and their client crashes to desktop.  Please note, Game Crash, not Server Crash.  Other players on the server are fine, after a short freeze.
When verifying this in Singleplayer, I was able to see that the mouse hover in JEI reads "tooltip error, see log"

The log reads 
[18:03:31] [main/ERROR]: Failed to get tooltip: 1 whoopee_cushion artifacts:whoopee_cushion
java.lang.NullPointerException: null

**To Reproduce**

reproduceable on several servers running the same pack.  similar issues on single player.  JEI was able to give more info.  please note, i am able to have this in my inventory without crashes, and I am able to fetch it from JEI cheat mode without crashes.  but as soon as the cursor points at the item in an inventory, the game will crash.

1. find a chest or other inventory that includes a whoopee cushion.  <item:artifacts:whoopee_cushion>
2. hover over the item icon in the inventory.  
3. your game will freeze and the client will crash.  single player and multiplayer.

The extended log section is:  [18:03:31] [main/ERROR]: Failed to get tooltip: 1 whoopee_cushion artifacts:whoopee_cushion
java.lang.NullPointerException: null
	at it.hurts.sskirillss.relics.client.tooltip.TooltipDescriptionHandler.lambda$renderState$0(TooltipDescriptionHandler.java:86) ~[?:0.3.2.1]
	at it.hurts.sskirillss.relics.client.tooltip.TooltipDescriptionHandler$$Lambda$16114/1200286359.accept(Unknown Source) ~[?:?]
	at net.minecraftforge.common.util.LazyOptional.ifPresent(LazyOptional.java:165) ~[?:?]
	at it.hurts.sskirillss.relics.client.tooltip.TooltipDescriptionHandler.renderState(TooltipDescriptionHandler.java:78) ~[?:0.3.2.1]
	at it.hurts.sskirillss.relics.client.tooltip.TooltipDescriptionHandler.onTooltipRender(TooltipDescriptionHandler.java:44) ~[?:0.3.2.1]
	at net.minecraftforge.eventbus.ASMEventHandler_443_TooltipDescriptionHandler_onTooltipRender_ItemTooltipEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus$$Lambda$3348/1380932670.invoke(Unknown Source) ~[?:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.event.ForgeEventFactory.onItemTooltip(ForgeEventFactory.java:289) ~[?:?]
	at net.minecraft.item.ItemStack.func_82840_a(ItemStack.java:701) ~[?:?]
	at mezz.jei.plugins.vanilla.ingredients.item.ItemStackRenderer.getTooltip(ItemStackRenderer.java:53) [?:7.7.1.138]
	at mezz.jei.plugins.vanilla.ingredients.item.ItemStackRenderer.getTooltip(ItemStackRenderer.java:26) [?:7.7.1.138]
	at mezz.jei.render.IngredientRenderHelper.getIngredientTooltipSafe(IngredientRenderHelper.java:25) [?:7.7.1.138]
	at mezz.jei.render.IngredientListElementRenderer.getTooltip(IngredientListElementRenderer.java:121) [?:7.7.1.138]
	at mezz.jei.render.IngredientListElementRenderer.drawTooltip(IngredientListElementRenderer.java:103) [?:7.7.1.138]
	at mezz.jei.gui.overlay.IngredientGrid.drawTooltips(IngredientGrid.java:156) [?:7.7.1.138]
	at mezz.jei.gui.overlay.IngredientGridWithNavigation.drawTooltips(IngredientGridWithNavigation.java:134) [?:7.7.1.138]
	at mezz.jei.gui.overlay.IngredientListOverlay.drawTooltips(IngredientListOverlay.java:194) [?:7.7.1.138]
	at mezz.jei.gui.GuiEventHandler.onDrawScreenEventPost(GuiEventHandler.java:143) [?:7.7.1.138]
	at mezz.jei.gui.GuiEventHandler$$Lambda$16204/2065971153.accept(Unknown Source) [?:7.7.1.138]
	at mezz.jei.events.EventBusHelper.lambda$registerWeakListener$2(EventBusHelper.java:116) [?:7.7.1.138]
	at mezz.jei.events.EventBusHelper$$Lambda$16095/989398827.accept(Unknown Source) [?:7.7.1.138]
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) [eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) [eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus$$Lambda$3031/606391197.invoke(Unknown Source) [eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus$$Lambda$3348/1380932670.invoke(Unknown Source) [eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) [eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) [eventbus-4.0.0.jar:?]
	at net.minecraftforge.client.ForgeHooksClient.drawScreenInternal(ForgeHooksClient.java:378) [?:?]
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:370) [?:?]
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:492) [?:?]
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:977) [?:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) [?:?]
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.5-36.2.22.jar:36.2]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$492/110233108.call(Unknown Source) [forge-1.16.5-36.2.22.jar:36.2]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?]

**Game Environment**
Please provide details about the game environment, either by crash report/logs or by detailing it below.
 - Artifacts: Artifacts-1.16.5-2.10.4.jar
 - Forge: Forge 36.2.22
 - Curios, Expandability, Relics, Nameless Trinkets, CraftTweaker, Lootr, there are over 100... if you need the full list, i can provide you with the export.

**Comment by ochotonida** [comment]
Thanks for the report. - Please post logs on a pasting site, putting them in a comment clutters up the conversation.

This appears to be an issue with Relics, I believe updating it to the latest version (0.3.3) should fix this issue. If the issue persists after updating I suggest reporting it to them, as this issue doesn't seem to be caused by Artifacts.
