### ISSUE TITLE
1.19.2 Crash: Server Closed; using Chunk Pregenerator

### ISSUE THREAD

**Issue by Daltaxy** [ochotonida/artifacts#197]
**Describe the bug**
Crash using Chunk Pregenerator. I was generating 250 chunks and not even 2 minutes into the generation, the server closed.
log:
<details><summary>latest.log</summary>
<p>
[20Mar2023 16:35:52.839] [Worker-Main-3/WARN] [com.structureessentials.StructureEssentials/]: Feature: ResourceKey[minecraft:worldgen/configured_feature / artifacts:campsite] errored during placement at BlockPos{x=272, y=-64, z=-160}
[20Mar2023 16:35:52.838] [Server thread/ERROR] [net.minecraft.server.MinecraftServer/]: Exception stopping the server
java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 8193
	at it.unimi.dsi.fastutil.longs.Long2ObjectLinkedOpenHashMap.moveIndexToLast(Long2ObjectLinkedOpenHashMap.java:504) ~[fastutil-8.5.6.jar%23127!/:?]
	at it.unimi.dsi.fastutil.longs.Long2ObjectLinkedOpenHashMap.getAndMoveToLast(Long2ObjectLinkedOpenHashMap.java:571) ~[fastutil-8.5.6.jar%23127!/:?]
	at pregenerator.common.utils.collections.Long2ObjectCustomMap.get(Long2ObjectCustomMap.java:89) ~[Chunk%20Pregenerator-1.19-4.2.2.jar%23697!/:1.19-4.2.2]
	at net.minecraft.world.level.chunk.storage.SectionStorage.m_63798_(SectionStorage.java:179) ~[client-1.19.2-20220805.130853-srg.jar%231069!/:?]
	at net.minecraft.world.level.chunk.storage.SectionStorage.m_63825_(SectionStorage.java:165) ~[client-1.19.2-20220805.130853-srg.jar%231069!/:?]
	at net.minecraft.world.level.chunk.storage.SectionStorage.m_6202_(SectionStorage.java:69) ~[client-1.19.2-20220805.130853-srg.jar%231069!/:?]
	at net.minecraft.world.entity.ai.village.poi.PoiManager.m_6202_(PoiManager.java:190) ~[client-1.19.2-20220805.130853-srg.jar%231069!/:?]
	at net.minecraft.server.level.ChunkMap.m_140280_(ChunkMap.java:438) ~[client-1.19.2-20220805.130853-srg.jar%231069!/:?]
	at net.minecraft.server.level.ServerChunkCache.m_201698_(ServerChunkCache.java:314) ~[client-1.19.2-20220805.130853-srg.jar%231069!/:?]
	at net.minecraft.server.MinecraftServer.m_7041_(MinecraftServer.java:567) ~[client-1.19.2-20220805.130853-srg.jar%231069!/:?]
	at net.minecraft.client.server.IntegratedServer.m_7041_(IntegratedServer.java:173) ~[client-1.19.2-20220805.130853-srg.jar%231069!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:682) ~[client-1.19.2-20220805.130853-srg.jar%231069!/:?]
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:244) ~[client-1.19.2-20220805.130853-srg.jar%231069!/:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
[20Mar2023 16:35:53.575] [Render thread/DEBUG] [Tips/]: Displaying tip tipsmod:bed_explode on screen ProgressScreen.
[20Mar2023 16:35:58.673] [Render thread/DEBUG] [Tips/]: Displaying tip tipsmod:fossils on screen ProgressScreen.
[20Mar2023 16:36:03.733] [Render thread/DEBUG] [Tips/]: Displaying tip tipsmod:mooshroom_lightning on screen ProgressScreen.
[20Mar2023 16:36:08.830] [Render thread/DEBUG] [Tips/]: Displaying tip tipsmod:piglin_repellent on screen ProgressScreen.
[20Mar2023 16:36:12.731] [Server thread/DEBUG] [net.minecraftforge.registries.ObjectHolderRef/]: Unable to lookup rusticregen:crossed_logs for public static net.minecraft.world.level.block.Block cjminecraft.doubleslabs.api.support.rusticregen.RusticRegenSlabSupport.CROSSED_LOGS. This means the object wasn't registered. It's likely just mod options.
[20Mar2023 16:36:12.748] [Server thread/DEBUG] [FluxNetworks/]: FluxNetworkData has been unloaded
[20Mar2023 16:36:12.752] [Server thread/DEBUG] [SpectreLib/CONFIG]: Unloading server configs
[20Mar2023 16:36:12.755] [Server thread/INFO] [configured/]: Unloading server configs...
[20Mar2023 16:36:12.757] [Server thread/DEBUG] [net.minecraftforge.fml.loading.FileUtils/CORE]: Found existing serverconfig directory : C:\Users\david\Twitch\Minecraft\Instances\Daltaxy\saves\Finally, Daltaxy_\serverconfig
[20Mar2023 16:36:12.757] [Server thread/DEBUG] [net.minecraftforge.fml.config.ConfigTracker/CONFIG]: Unloading configs type SERVER
[20Mar2023 16:36:12.866] [Render thread/INFO] [ChunkBuilder/]: Stopping worker threads

</p>
</details> 

Crash Report: 
[crash-2023-03-20_08.37.13-server.txt](https://github.com/ochotonida/artifacts/files/11020530/crash-2023-03-20_08.37.13-server.txt)

I know this will look ridiculous but ChatGPT's answer:
<details><summary>Answer</summary>
<p>
The first error that appears in the log is an "ArrayIndexOutOfBoundsException" caused by a "SectionStorage" issue while placing a "Feature". This could be due to an issue with the "Chunk Pregenerator" mod, which appears to be causing a conflict with "minecraft:worldgen/configured_feature/artifacts:campsite". It is possible that the mod is causing this issue by trying to access an invalid index in an array with a negative value. This is a serious error that has caused the server to stop.

</p>
</details> 

**To Reproduce**
Depends on when the campsite is generated, I guess?

**Game Environment**
Please provide details about the game environment, either by crash report/logs or by detailing it below. Try to reproduce the issue without irrelevant mods first. Otherwise, include a complete list of mods or the name and version of the modpack you're using.
 - Artifacts: artifacts-1.19.2-5.0.2.jar
 - Forge: 43.2.7
 - Chunk Pregenerator, Essential

**Comment by ochotonida** [comment]
Did you reproduce this with just the mods listed in your issue? I can't seem to be able to reproduce this, and your crash report has a lot more mods that just the ones you listed.
Also, please include a full log next time, either by uploading the file here or using a site like pastebin. It's not particulary easy to read an error message when there's no context and all the lines are concatenated together.

**Comment by Daltaxy** [comment]
> Did you reproduce this with just the mods listed in your issue? I can't seem to be able to reproduce this, and your crash report has a lot more mods that just the ones you listed. Also, please include a full log next time, either by uploading the file here or using a site like pastebin. It's not particulary easy to read an error message when there's no context and all the lines are concatenated together.

log was too heavy so I thought I'd upload crash report instead. I'll try to generate now. Maybe it is caused by a conflict? could you quote the "lot more mods" that were possibly in cause? I have about 450 mods loaded but I don't think a lot were mentioned {in cause} in the crash report, no? 
I totally understand the unreadable part, I'll try and keep you up with the new logs, sorry about that.
I think it was Canary personally. The problem is that starting the game, the world and the pregeneration takes 30 minutes to do each time. https://github.com/AbdElAziz333/Canary/issues: so many crash issues when loading chunks/starting a new world...
Hence, I will try without Canary, without Artifacts, then with Canary, with Artifacts.
quick edit: it could also be due to Blue Skies. I wonder why and how that affects your campfire generation though...

**Comment by Daltaxy** [comment]
With Artifacts, with Canary: crash before loading 15 chunks.
Without Artifacts, with Canary: crash before loading 200 chunks.
Without Artifacts, without Canary: 4923 chunks loaded, no crash. Is it safe to say that it won't crash?
With Artifacts Without Canary: now the game crashes on world creation for whatever reason??? and it's not linked to Artifcats? wtf...
https://bytebin.lucko.me/Ef2OSd235j
also, thank god github keeps drafts of what we write

**Comment by ochotonida** [comment]
It seems to be a compatibility issue between canary & chunk pregenerator, chunk pregenerator lists Lithium as a known incompatability: https://github.com/TinyModularThings/Chunk-Pregenerator-Issue-Tracker/issues/2. The issue is related to POI's (workstations for villagers, like smithing tables etc.). Campsites usually contain a few of those which explains why you're crashing sooner with Artifacts installed.

> could you quote the "lot more mods" that were possibly in cause? I have about 450 mods loaded but I don't think a lot were mentioned {in cause} in the crash report, no?

I didn't have anything specific in mind in terms of what is causing it, but the issue template specifically asks to either try to reproduce with irrelevant mods first or to list all mods/modpack you're using. That's why I assumed the issue was reproducable with just the mods you listed.
If an issue is consistently reproducable and you have a lot of mods it's usually a good idea to at least check whether it still happens after removing the mod you think is causing it before reporting it to the mod's developer(s).
