### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by WenXin20** [ochotonida/artifacts#20]
`Minecraft v1.15.2`
`Forge v31.2.31`
`Artifacts v2.1.0`

The Kitty Slippers crashes the game server side. The previous version worked fine on the server.
[Crash Report](https://gist.github.com/WenXin20/21eecc4166f2d96ed43b0bd5caaa7f0e)

**Comment by solarblindfull** [comment]
Hello ! Thank for this mod. Unfortunately, same crash here on my forge 31.2.30 server !

<details>
  <summary>Crash report</summary>
  
[Thread-1/ERROR] [net.minecraftforge.fml.javafmlmod.FMLModContainer/]: Exception caught during firing event: class artifacts.client.render.model.curio.KittySlippersModel cannot access its superclass net.minecraft.client.renderer.entity.model.BipedModel

	Index: 1

	Listeners:

		0: NORMAL

		1: ASM: class bl4ckscor3.mod.chanceglobe.ChanceGlobe onModConfigReloading(Lnet/minecraftforge/fml/config/ModConfig$Reloading;)V

java.lang.IllegalAccessError: class artifacts.client.render.model.curio.KittySlippersModel cannot access its superclass net.minecraft.client.renderer.entity.model.BipedModel

	at java.lang.ClassLoader.defineClass1(Native Method)

	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)

	at java.lang.ClassLoader.defineClass(ClassLoader.java:642)

	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:127)

	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:96)

	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)

	at artifacts.common.item.KittySlippersItem.initCapabilities(KittySlippersItem.java:35)

	at net.minecraft.item.ItemStack.forgeInit(ItemStack.java:956)

	at net.minecraft.item.ItemStack.<init>(ItemStack.java:109)

	at net.minecraft.item.ItemStack.<init>(ItemStack.java:98)

	at bl4ckscor3.mod.chanceglobe.ChanceGlobe.generateItemStacks(ChanceGlobe.java:110)

	at bl4ckscor3.mod.chanceglobe.ChanceGlobe.onModConfigReloading(ChanceGlobe.java:73)

	at net.minecraftforge.eventbus.ASMEventHandler_735_ChanceGlobe_onModConfigReloading_Reloading.invoke(.dynamic)

	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80)

	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258)

	at net.minecraftforge.fml.javafmlmod.FMLModContainer.lambda$new$0(FMLModContainer.java:66)

	at net.minecraftforge.fml.ModContainer.lambda$dispatchConfigEvent$5(ModContainer.java:147)

	at java.util.Optional.ifPresent(Optional.java:159)

	at net.minecraftforge.fml.ModContainer.dispatchConfigEvent(ModContainer.java:147)

	at net.minecraftforge.fml.config.ModConfig.fireEvent(ModConfig.java:89)

	at net.minecraftforge.fml.config.ConfigFileTypeHandler$ConfigWatcher.run(ConfigFileTypeHandler.java:104)

	at com.electronwill.nightconfig.core.file.FileWatcher$WatcherThread.run(FileWatcher.java:181)
    
</details>

**Comment by ochotonida** [comment]
Thanks for the report, sorry I didn't see this sooner. I'll release a fix asap.

**Comment by ochotonida** [comment]
I've released a patch that should fix the issue

**Comment by solarblindfull** [comment]
That works fine ! Thank for the very quick fix !
