### ISSUE TITLE
Network protocol error

### ISSUE THREAD

**Issue by CA117M** [ochotonida/artifacts#332]
BUG: When equipping / unequipping artifacts in the trinkets slots, sometimes (50%) booted to main menu from singleplayer due to "network protocol error"

**To Reproduce**
1. Equip an artifact in a trinket slot
2. Booted to main menu
3. ???
4. profit

**Game Environment**

I know there's a tonne of mods but these two mods interacting are the only time the crash occurs.

---- Minecraft Network Protocol Error Report ----
// 404

Time: 2024-10-13 18:12:44
Description: Packet handling error

java.lang.IndexOutOfBoundsException: Index 53 out of bounds for length 53
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:100)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:106)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:302)
	at java.base/java.util.Objects.checkIndex(Objects.java:385)
	at java.base/java.util.ArrayList.get(ArrayList.java:427)
	at net.minecraft.class_2371.get(class_2371.java:47)
	at net.minecraft.class_1703.method_7611(class_1703.java:287)
	at net.minecraft.class_1703.method_7619(class_1703.java:593)
	at net.minecraft.class_634.method_11109(class_634.java:1261)
	at net.minecraft.class_2653.method_11451(class_2653.java:49)
	at net.minecraft.class_2653.method_11054(class_2653.java:10)
	at net.minecraft.class_2600.method_11072(class_2600.java:27)
	at net.minecraft.class_1255.method_18859(class_1255.java:162)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.class_1255.method_16075(class_1255.java:136)
	at net.minecraft.class_1255.method_5383(class_1255.java:121)
	at net.minecraft.class_310.method_1523(class_310.java:1240)
	at net.minecraft.class_310.method_1514(class_310.java:882)
	at net.minecraft.client.main.Main.main(Main.java:256)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:100)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:106)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:302)
	at java.base/java.util.Objects.checkIndex(Objects.java:385)
	at java.base/java.util.ArrayList.get(ArrayList.java:427)
	at net.minecraft.class_2371.get(class_2371.java:47)
	at net.minecraft.class_1703.method_7611(class_1703.java:287)
	at net.minecraft.class_1703.method_7619(class_1703.java:593)

-- Incoming Packet --
Details:
	Type: clientbound/minecraft:container_set_slot
	Is Terminal: false
	Is Skippable: false
Stacktrace:
	at net.minecraft.class_2600.method_59803(class_2600.java:56)
	at net.minecraft.class_8673.method_60882(class_8673.java:136)
	at net.minecraft.class_8673.method_59807(class_8673.java:113)
	at net.minecraft.class_2600.method_11072(class_2600.java:32)
	at net.minecraft.class_1255.method_18859(class_1255.java:162)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.class_1255.method_16075(class_1255.java:136)
	at net.minecraft.class_1255.method_5383(class_1255.java:121)
	at net.minecraft.class_310.method_1523(class_310.java:1240)
	at net.minecraft.class_310.method_1514(class_310.java:882)
	at net.minecraft.client.main.Main.main(Main.java:256)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Connection --
Details:
	Protocol: play
	Flow: CLIENTBOUND
	Server type: <none>
	Server brand: fabric

-- System Details --
Details:
	Minecraft Version: 1.21.1
	Minecraft Version ID: 1.21.1
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 21.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 5612630600 bytes (5352 MiB) / 9663676416 bytes (9216 MiB) up to 9663676416 bytes (9216 MiB)
	CPUs: 20
	Processor Vendor: GenuineIntel
	Processor Name: 12th Gen Intel(R) Core(TM) i7-12700F
	Identifier: Intel64 Family 6 Model 151 Stepping 2
	Microarchitecture: Alder Lake
	Frequency (GHz): 2.11
	Number of physical packages: 1
	Number of physical CPUs: 12
	Number of logical CPUs: 20
	Graphics card #0 name: NVIDIA GeForce RTX 4070 Ti
	Graphics card #0 vendor: NVIDIA
	Graphics card #0 VRAM (MiB): 12282.00
	Graphics card #0 deviceId: VideoController1
	Graphics card #0 versionInfo: 31.0.15.4629
	Memory slot #0 capacity (MiB): 16384.00
	Memory slot #0 clockSpeed (GHz): 2.67
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MiB): 16384.00
	Memory slot #1 clockSpeed (GHz): 2.67
	Memory slot #1 type: DDR4
	Virtual memory max (MiB): 34643.97
	Virtual memory used (MiB): 23208.65
	Swap memory total (MiB): 2048.00
	Swap memory used (MiB): 0.00
	Space in storage for jna.tmpdir (MiB): available: 301742.66, total: 953031.50
	Space in storage for org.lwjgl.system.SharedLibraryExtractPath (MiB): available: 301742.66, total: 953031.50
	Space in storage for io.netty.native.workdir (MiB): available: 301742.66, total: 953031.50
	Space in storage for java.io.tmpdir (MiB): available: 301742.66, total: 953031.50
	Space in storage for workdir (MiB): available: 301742.66, total: 953031.50
	JVM Flags: 11 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx12G -Xmx9G -Xms9G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		ambientsounds: AmbientSounds 6.1.2
		amplified_nether: Amplified Nether 1.2.5
		architectury: Architectury 13.0.6
		artifacts: Artifacts 12.0.6
			com_electronwill_night-config_core: core 3.8.0
			com_electronwill_night-config_toml: toml 3.8.0
			expandability: ExpandAbility 12.0.0
		backslot: BackSlot 1.2.15
			amecsapi: Amecs API 1.5.5+mc1.20.2
		bettercombat: Better Combat 2.0.3+1.21.1
		biome_replacer: Biome Replacer 1.5
		biomemoss: Biome Moss 1.1.0
		cardinal-components: Cardinal Components API 6.1.1
			cardinal-components-base: Cardinal Components API (base) 6.1.1
			cardinal-components-block: Cardinal Components API (blocks) 6.1.1
			cardinal-components-chunk: Cardinal Components API (chunks) 6.1.1
			cardinal-components-entity: Cardinal Components API (entities) 6.1.1
			cardinal-components-item: Cardinal Components API (items) 6.1.1
			cardinal-components-level: Cardinal Components API (world saves) 6.1.1
			cardinal-components-scoreboard: Cardinal Components API (scoreboard) 6.1.1
			cardinal-components-world: Cardinal Components API (worlds) 6.1.1
		cloth-config: Cloth Config v15 15.0.130
			cloth-basic-math: cloth-basic-math 0.6.1
		collective: Collective 7.84
		connectiblechains: Connectible Chains 2.4.2+1.21.1
		creativecore: CreativeCore 2.12.16
			net_neoforged_bus: bus 7.2.0
		diagonalfences: Diagonal Fences 21.1.0
			diagonalblocks: Diagonal Blocks 21.1.0
		disable_custom_worlds_advice: Disable Custom Worlds Advice 6.0
		distanthorizons: Distant Horizons 2.2.1-a
			fabric-api-base: Fabric API Base 0.4.42+6573ed8c90
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.47+0af3f5a790
		doapi: [Let's Do] API 1.3.0-beta-release
			blue_endless_jankson: jankson 1.2.3
			terraform-wood-api-v1: Terraform Wood API (v1) 11.0.0-alpha.1
		easyanvils: Easy Anvils 21.1.0
		elixirum: Ars Elixirum 0.1.1
		entity_model_features: Entity Model Features 2.2.6
		entity_texture_features: Entity Texture Features 6.2.5
			org_apache_httpcomponents_httpmime: httpmime 4.5.10
		entityculling: EntityCulling 1.7.0
		evs: Enchanted Vertical Slabs 2.3
		explosiveenhancement: Explosive Enhancement 1.2.3-1.21.0
		fabric-api: Fabric API 0.103.0+1.21.1
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.68+b559734419
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.29+5bd9f1bc19
			fabric-block-api-v1: Fabric Block API (v1) 1.0.22+0af3f5a719
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.10+6573ed8c19
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.52+0af3f5a719
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.15+6573ed8c19
			fabric-command-api-v1: Fabric Command API (v1) 1.2.49+f71b366f19
			fabric-command-api-v2: Fabric Command API (v2) 2.2.28+6ced4dd919
			fabric-commands-v0: Fabric Commands (v0) 0.2.66+df3654b319
			fabric-content-registries-v0: Fabric Content Registries (v0) 8.0.16+b559734419
			fabric-convention-tags-v1: Fabric Convention Tags 2.0.21+7f945d5b19
			fabric-convention-tags-v2: Fabric Convention Tags (v2) 2.6.1+9b16164119
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.29+0af3f5a719
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.1.28+1daea21519
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 20.2.18+16c4ae2519
			fabric-dimensions-v1: Fabric Dimensions API (v1) 4.0.0+6fc22b9919
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.7.0+2122d82819
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.7.12+ba9dae0619
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.53+6ced4dd919
			fabric-item-api-v1: Fabric Item API (v1) 11.0.0+afdfc92119
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.1.5+3fc0e55219
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.45+df3654b319
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.3.12+6c1df36019
			fabric-loot-api-v2: Fabric Loot API (v2) 3.0.14+3f89f5a519
			fabric-loot-api-v3: Fabric Loot API (v3) 1.0.2+3f89f5a519
			fabric-message-api-v1: Fabric Message API (v1) 6.0.13+6573ed8c19
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 2.0.0+fe474d6b19
			fabric-networking-api-v1: Fabric Networking API (v1) 4.2.2+60c3209b19
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 15.2.0+40875a9319
			fabric-particles-v1: Fabric Particles (v1) 4.0.2+6573ed8c19
			fabric-recipe-api-v1: Fabric Recipe API (v1) 5.0.12+6508971219
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 5.1.2+60c3209b19
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.4.0+c705a49c19
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.7.0+c705a49c19
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.68+df3654b319
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.48+73761d2e19
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.1.6+1daea21519
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.71+df3654b319
			fabric-rendering-v1: Fabric Rendering (v1) 5.0.5+df16efd019
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 4.3.0+8dc279b119
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 1.3.0+5659912919
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.25+8b68f1c719
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.86+b559734419
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.23+6573ed8c19
			fabric-transfer-api-v1: Fabric Transfer API (v1) 5.1.17+1db1cc1f19
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 6.1.0+1daea21519
		fabricloader: Fabric Loader 0.16.5
			mixinextras: MixinExtras 0.4.1
		fallingleaves: Falling Leaves 1.16.2
		farm_and_charm: [Let's Do] Farm & Charm 1.2.0-beta-release
		ferritecore: FerriteCore 7.0.0
		firstperson: FirstPerson 2.4.5
		forgeconfigapiport: Forge Config API Port 21.1.1
		friendsandfoes: Friends & Foes 3.0.3
		geophilic: Geophilic 3.1.3
		iris: Iris 1.8.0-beta.4+mc1.21.1
			io_github_douira_glsl-transformer: glsl-transformer 2.0.1
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.13.1
		java: OpenJDK 64-Bit Server VM 21
		lithium: Lithium 0.13.1
		minecraft: Minecraft 1.21.1
		modmenu: Mod Menu 11.0.2
			placeholder-api: Placeholder API 2.4.0-pre.2+1.21
		mr_no_endermangrief: No Enderman Grief 1-v.2.1.2
		mr_true_ending: True Ending: Ender Dragon Overhaul 1-v1.1.2d
		mr_wither_shrines: Wither Shrines 1.1.1
		nullscape: Nullscape 1.2.7
		offlineskins: OfflineSkins 1.21.1-v1a-fabric
		owo: oωo 0.12.10+1.21
			io_wispforest_endec: endec 0.1.0
			io_wispforest_endec_gson: gson 0.1.0
			io_wispforest_endec_jankson: jankson 0.1.0
			io_wispforest_endec_netty: netty 0.1.0
		particular: Particular 1.1.1+1.21
		playeranimator: Player Animator 2.0.0-alpha1+1.21
		presencefootsteps: Presence Footsteps 1.10.0+1.21
			kirin: Kirin UI 1.19.0+1.21
		puzzleslib: Puzzles Lib 21.1.18
		shelf-mod: shelf-mod 1.0
		simple_copper_pipes: Simple Copper Pipes 2.0
		skinlayers3d: 3d-Skin-Layers 1.6.7
		sodium: Sodium 0.6.0-beta.2+mc1.21.1
		sound_physics_remastered: Sound Physics Remastered 1.21.1-1.4.6
		thecopperrail: The Copper Rail 0.9.4
		tia: Tiny Item Animations 1.2.1
		trinkets: Trinkets 3.10.0
		voicechat: Simple Voice Chat 1.21.1-2.5.23
		wilderwild: Wilder Wild 2.4.16-mc1.21.1
			frozenlib: FrozenLib 1.8.6-mc1.21.1
		worldedit: WorldEdit 7.3.6+6892-3d660b8
	Loaded Shaderpack: BSLOriginal_v8.3.zip
		Profile: Custom (+59 options changed by user)

**Comment by ochotonida** [comment]
This is very likely an issue with Trinkets rather than with Artifacts. Artifacts doesn't send any data between the server and client when items are equipped or unequipped, this all gets handled by Trinkets.
