### ISSUE TITLE
Minecraft 1.16.2 Ran with only Trinkets

### ISSUE THREAD

**Issue by LuKeLyW** [ochotonida/artifacts#37]
---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 11/7/20 3:24 AM
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'artifacts'!
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:53)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:36)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient.start(EntrypointClient.java:32)
	at net.minecraft.class_310.<init>(class_310.java:423)
	at net.minecraft.client.main.Main.main(Main.java:177)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
Caused by: java.lang.NoClassDefFoundError: net/fabricmc/fabric/api/biome/v1/BiomeSelectors
	at artifacts.common.init.Features.register(Features.java:42)
	at artifacts.Artifacts.onInitialize(Artifacts.java:52)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient$$Lambda$2243/1709848929.accept(Unknown Source)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50)
	... 11 more
Caused by: java.lang.ClassNotFoundException: net.fabricmc.fabric.api.biome.v1.BiomeSelectors
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:161)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 15 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:53)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:36)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient.start(EntrypointClient.java:32)
	at net.minecraft.class_310.<init>(class_310.java:423)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:177)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)

-- System Details --
Details:
	Minecraft Version: 1.16.2
	Minecraft Version ID: 1.16.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 970440112 bytes (925 MB) / 1744830464 bytes (1664 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 12
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		artifacts: Artifacts 1.0.2+1.16.4-fabric
		autoconfig1u: Auto Config v1 Updated 3.2.2
		cardinal-components-base: Cardinal Components API (base) 2.7.2
		cardinal-components-entity: Cardinal Components API (entities) 2.7.2
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-config2: Cloth Config v4 4.8.2
		fabric: Fabric API 0.20.1+build.401-1.16
		fabric-api-base: Fabric API Base 0.1.3+12a8474c4e
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.4+c6a8ea894e
		fabric-command-api-v1: Fabric Command API (v1) 1.0.8+5ce533984e
		fabric-commands-v0: Fabric Commands (v0) 0.2.0+52d308364e
		fabric-containers-v0: Fabric Containers (v0) 0.1.8+045df74f4e
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.1.9+059ea8664e
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825d4e
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.0+e2e6cdad4e
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.0+16acbe5b4e
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.1+91555cd14e
		fabric-item-api-v1: Fabric Item API (v1) 1.1.0+29679fd64e
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.0+438f96364e
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.1+730711c64e
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.0+3fa9f7c54e
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.0+74cc3b204e
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.1+432ea1884e
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.2+b764ce994e
		fabric-models-v0: Fabric Models (v0) 0.1.0+dfdb52d64e
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.5+b50ffc7b4e
		fabric-networking-v0: Fabric Networking (v0) 0.1.10+e00ecb5f4e
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.7.0+432ea1884e
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.0+432ea1884e
		fabric-particles-v1: fabric-particles-v1 0.2.2+fb0d9b0e4e
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.4.5+fcdfdfa14e
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.3.0+8bcfced84e
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.0+8bcfced84e
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.1.0+e2862de64e
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.3+b7f9825d4e
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.11+fb0d9b0e4e
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.0+534104904e
		fabric-rendering-v1: Fabric Rendering (v1) 1.3.0+432ea1884e
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.3.1+facf3bbf4e
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.0+872498414e
		fabric-structure-api-v1: Fabric Structure API (v1) 1.0.1+fb0d9b0e4e
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.0.3+ac8e8c594e
		fabric-textures-v0: Fabric Textures (v0) 1.0.4+eae12eb84e
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.2+ccce563e4e
		fabricloader: Fabric Loader 0.9.2+build.206
		minecraft: Minecraft 1.16.2
		step-height-entity-attribute: Step Height Entity Attribute 1.0.0
		trinkets: Trinkets 2.6.4
	Launched Version: fabric-loader-0.9.2+build.206-1.16.2
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NO CONTEXT
	GL Caps: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	CPU: <unknown>

**Comment by florensie** [comment]
This is the repository for the Forge version of Artifacts. You can find the Fabric repository here: https://github.com/florensie/artifacts-fabric In the future, please post your issues with Artifacts for Fabric there.

Your issue should be solved by downloading the latest version of fabric api however. If that doesn't solve the problem please open a new issue on my github repo.
