### ISSUE TITLE
'Artifacts has failed to load correctly - Type net.minecraftforge.common.lootGlobalLootModifierSerializer not present'

### ISSUE THREAD

**Issue by AddAmazeing** [ochotonida/artifacts#64]
![Screenshot 2021-02-18 160216](https://user-images.githubusercontent.com/79289593/108437809-ddb41600-7202-11eb-8260-f044a4fe53cb.png)

**Comment by AddAmazeing** [comment]
I only have these the Artifact and Curious API mods installed and I have this error whenever I try to boot up Minecraft version 1.14.4 with these mods. Here are the logs, any help would be greatly appreciated :]:

 [18Feb2021 15:44:24.342] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher running: args [--username, zefereater, --version, 1.14.4-forge-28.2.0, --gameDir, C:\Users\AddAm\AppData\Roaming\.minecraft, --assetsDir, C:\Users\AddAm\AppData\Roaming\.minecraft\assets, --assetIndex, 1.14, --uuid, 66a96378f77849f68198fef380137a54, --accessToken, ????????, --userType, mojang, --versionType, release, --launchTarget, fmlclient, --fml.forgeVersion, 28.2.0, --fml.mcVersion, 1.14.4, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20190829.143755]
[18Feb2021 15:44:24.346] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher 4.1.0+62+5bfa59b starting: java version 1.8.0_51 by Oracle Corporation
[18Feb2021 15:44:24.624] [main/INFO] [net.minecraftforge.fml.loading.FixSSL/CORE]: Added Lets Encrypt root certificates as additional trust
[18Feb2021 15:44:25.747] [main/INFO] [cpw.mods.modlauncher.LaunchServiceHandler/MODLAUNCHER]: Launching target 'fmlclient' with arguments [--version, 1.14.4-forge-28.2.0, --gameDir, C:\Users\AddAm\AppData\Roaming\.minecraft, --assetsDir, C:\Users\AddAm\AppData\Roaming\.minecraft\assets, --uuid, 66a96378f77849f68198fef380137a54, --username, zefereater, --assetIndex, 1.14, --accessToken, ????????, --userType, mojang, --versionType, release]
[18Feb2021 15:44:27.917] [Client thread/INFO] [net.minecraft.client.Minecraft/]: Setting user: zefereater
[18Feb2021 15:44:38.165] [Client thread/INFO] [net.minecraft.client.Minecraft/]: LWJGL Version: 3.2.2 build 10
[18Feb2021 15:44:42.065] [Client thread/WARN] [net.minecraft.client.GameSettings/]: Removed resource pack mod_resources from options because it doesn't seem to exist anymore
[18Feb2021 15:44:42.728] [modloading-worker-3/INFO] [net.minecraftforge.common.ForgeMod/FORGEMOD]: Forge mod loading, version 28.2.0, for MC 1.14.4 with MCP 20190829.143755
[18Feb2021 15:44:42.729] [modloading-worker-3/INFO] [net.minecraftforge.common.MinecraftForge/FORGE]: MinecraftForge v28.2.0 Initialized
[18Feb2021 15:44:42.976] [modloading-worker-2/ERROR] [net.minecraftforge.fml.javafmlmod.FMLModContainer/LOADING]: Failed to register automatic subscribers. ModID: artifacts, class artifacts.Artifacts
java.lang.TypeNotPresentException: Type net.minecraftforge.common.loot.GlobalLootModifierSerializer not present
	at sun.reflect.generics.factory.CoreReflectionFactory.makeNamedType(CoreReflectionFactory.java:117) ~[?:1.8.0_51]
	at sun.reflect.generics.visitor.Reifier.visitClassTypeSignature(Reifier.java:125) ~[?:1.8.0_51]
	at sun.reflect.generics.tree.ClassTypeSignature.accept(ClassTypeSignature.java:49) ~[?:1.8.0_51]
	at sun.reflect.generics.visitor.Reifier.reifyTypeArguments(Reifier.java:68) ~[?:1.8.0_51]
	at sun.reflect.generics.visitor.Reifier.visitClassTypeSignature(Reifier.java:138) ~[?:1.8.0_51]
	at sun.reflect.generics.tree.ClassTypeSignature.accept(ClassTypeSignature.java:49) ~[?:1.8.0_51]
	at sun.reflect.generics.repository.ConstructorRepository.getParameterTypes(ConstructorRepository.java:94) ~[?:1.8.0_51]
	at java.lang.reflect.Executable.getGenericParameterTypes(Executable.java:284) ~[?:1.8.0_51]
	at java.lang.reflect.Method.getGenericParameterTypes(Method.java:282) ~[?:1.8.0_51]
	at net.minecraftforge.eventbus.ASMEventHandler.<init>(ASMEventHandler.java:58) ~[eventbus-1.0.0-service.jar:?]
	at net.minecraftforge.eventbus.EventBus.register(EventBus.java:219) ~[eventbus-1.0.0-service.jar:?]
	at net.minecraftforge.eventbus.EventBus.registerListener(EventBus.java:138) ~[eventbus-1.0.0-service.jar:?]
	at net.minecraftforge.eventbus.EventBus.lambda$registerClass$2(EventBus.java:72) ~[eventbus-1.0.0-service.jar:?]
	at net.minecraftforge.eventbus.EventBus$$Lambda$2217/1677676577.accept(Unknown Source) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) ~[?:1.8.0_51]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[?:1.8.0_51]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[?:1.8.0_51]
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948) ~[?:1.8.0_51]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512) ~[?:1.8.0_51]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502) ~[?:1.8.0_51]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[?:1.8.0_51]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[?:1.8.0_51]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_51]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418) ~[?:1.8.0_51]
	at net.minecraftforge.eventbus.EventBus.registerClass(EventBus.java:72) ~[eventbus-1.0.0-service.jar:?]
	at net.minecraftforge.eventbus.EventBus.register(EventBus.java:112) ~[eventbus-1.0.0-service.jar:?]
	at net.minecraftforge.fml.AutomaticEventSubscriber.lambda$inject$3(AutomaticEventSubscriber.java:70) ~[?:?]
	at net.minecraftforge.fml.AutomaticEventSubscriber$$Lambda$2208/2139010374.accept(Unknown Source) ~[?:?]
	at java.util.ArrayList.forEach(ArrayList.java:1249) ~[?:1.8.0_51]
	at net.minecraftforge.fml.AutomaticEventSubscriber.inject(AutomaticEventSubscriber.java:57) ~[?:?]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:141) [?:28.2]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer$$Lambda$2111/1335405617.accept(Unknown Source) [?:28.2]
	at java.util.function.Consumer.lambda$andThen$14(Consumer.java:65) [?:1.8.0_51]
	at java.util.function.Consumer$$Lambda$2110/823101957.accept(Unknown Source) [?:1.8.0_51]
	at java.util.function.Consumer.lambda$andThen$14(Consumer.java:65) [?:1.8.0_51]
	at java.util.function.Consumer$$Lambda$2110/823101957.accept(Unknown Source) [?:1.8.0_51]
	at net.minecraftforge.fml.ModContainer.transitionState(ModContainer.java:112) [?:?]
	at net.minecraftforge.fml.ModList.lambda$null$10(ModList.java:134) [?:?]
	at net.minecraftforge.fml.ModList$$Lambda$2161/1837004885.accept(Unknown Source) [?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) [?:1.8.0_51]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374) [?:1.8.0_51]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512) [?:1.8.0_51]
	at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:291) [?:1.8.0_51]
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731) [?:1.8.0_51]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) [?:1.8.0_51]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) [?:1.8.0_51]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689) [?:1.8.0_51]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) [?:1.8.0_51]
Caused by: java.lang.ClassNotFoundException: net.minecraftforge.common.loot.GlobalLootModifierSerializer
	at java.lang.ClassLoader.findClass(ClassLoader.java:530) ~[?:1.8.0_51]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_51]
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:103) ~[modlauncher-4.1.0.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_51]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_51]
	at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_51]
	at sun.reflect.generics.factory.CoreReflectionFactory.makeNamedType(CoreReflectionFactory.java:114) ~[?:1.8.0_51]
	... 47 more
[18Feb2021 15:44:43.025] [Client thread/FATAL] [net.minecraftforge.fml.ModLoader/LOADING]: Failed to complete lifecycle event CONSTRUCT, 1 errors found
[18Feb2021 15:44:43.026] [Client thread/FATAL] [net.minecraftforge.eventbus.EventBus/EVENTBUS]: EventBus 0 shutting down - future events will not be posted.
java.lang.Exception: stacktrace
	at net.minecraftforge.eventbus.EventBus.shutdown(EventBus.java:278) [eventbus-1.0.0-service.jar:?]
	at net.minecraftforge.fml.client.ClientModLoader.lambda$createRunnableWithCatch$5(ClientModLoader.java:115) [?:?]
	at net.minecraftforge.fml.client.ClientModLoader$$Lambda$2002/1338446903.run(Unknown Source) [?:?]
	at net.minecraftforge.fml.client.ClientModLoader.begin(ClientModLoader.java:97) [?:?]
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:454) [?:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:365) [?:?]
	at net.minecraft.client.main.Main.main(SourceFile:155) [?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56) [forge-1.14.4-28.2.0.jar:28.2]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$402/24097622.call(Unknown Source) [forge-1.14.4-28.2.0.jar:28.2]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-4.1.0.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-4.1.0.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-4.1.0.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-4.1.0.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-4.1.0.jar:?]
[18Feb2021 15:44:45.324] [Client thread/INFO] [com.mojang.text2speech.NarratorWindows/]: Narrator library for x64 successfully loaded
[18Feb2021 15:44:45.661] [Server-Worker-1/ERROR] [net.minecraftforge.fml.ModLoader/LOADING]: Skipping lifecycle event SETUP, 1 errors found.
[18Feb2021 15:44:45.662] [Server-Worker-1/FATAL] [net.minecraftforge.fml.ModLoader/LOADING]: Failed to complete lifecycle event SETUP, 1 errors found
[18Feb2021 15:44:45.662] [Server-Worker-1/FATAL] [net.minecraftforge.eventbus.EventBus/EVENTBUS]: EventBus 0 shutting down - future events will not be posted.
java.lang.Exception: stacktrace
	at net.minecraftforge.eventbus.EventBus.shutdown(EventBus.java:278) [eventbus-1.0.0-service.jar:?]
	at net.minecraftforge.fml.client.ClientModLoader.lambda$createRunnableWithCatch$5(ClientModLoader.java:115) [?:?]
	at net.minecraftforge.fml.client.ClientModLoader$$Lambda$2002/1338446903.run(Unknown Source) [?:?]
	at net.minecraftforge.fml.client.ClientModLoader.startModLoading(ClientModLoader.java:123) [?:?]
	at net.minecraftforge.fml.client.ClientModLoader.lambda$onreload$3(ClientModLoader.java:105) [?:?]
	at net.minecraftforge.fml.client.ClientModLoader$$Lambda$2374/1773041202.run(Unknown Source) [?:?]
	at net.minecraftforge.fml.client.ClientModLoader.lambda$createRunnableWithCatch$5(ClientModLoader.java:113) [?:?]
	at net.minecraftforge.fml.client.ClientModLoader$$Lambda$2002/1338446903.run(Unknown Source) [?:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1618) [?:1.8.0_51]
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1610) [?:1.8.0_51]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) [?:1.8.0_51]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) [?:1.8.0_51]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689) [?:1.8.0_51]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) [?:1.8.0_51]
[18Feb2021 15:44:48.097] [Server-Worker-4/WARN] [net.minecraft.client.renderer.model.BlockModel/]: Unable to resolve texture due to upward reference: #stem in minecraft:block/pumpkin_stem_stage0
[18Feb2021 15:44:48.131] [Server-Worker-4/WARN] [net.minecraft.client.renderer.model.BlockModel/]: Unable to resolve texture due to upward reference: #stem in minecraft:block/pumpkin_stem_stage5
[18Feb2021 15:44:48.131] [Server-Worker-4/WARN] [net.minecraft.client.renderer.model.BlockModel/]: Unable to resolve texture due to upward reference: #stem in minecraft:block/pumpkin_stem_stage6
[18Feb2021 15:44:48.132] [Server-Worker-4/WARN] [net.minecraft.client.renderer.model.BlockModel/]: Unable to resolve texture due to upward reference: #stem in minecraft:block/pumpkin_stem_stage7
[18Feb2021 15:44:48.132] [Server-Worker-4/WARN] [net.minecraft.client.renderer.model.BlockModel/]: Unable to resolve texture due to upward reference: #stem in minecraft:block/pumpkin_stem_stage1
[18Feb2021 15:44:48.132] [Server-Worker-4/WARN] [net.minecraft.client.renderer.model.BlockModel/]: Unable to resolve texture due to upward reference: #stem in minecraft:block/pumpkin_stem_stage2
[18Feb2021 15:44:48.132] [Server-Worker-4/WARN] [net.minecraft.client.renderer.model.BlockModel/]: Unable to resolve texture due to upward reference: #stem in minecraft:block/pumpkin_stem_stage3
[18Feb2021 15:44:48.132] [Server-Worker-4/WARN] [net.minecraft.client.renderer.model.BlockModel/]: Unable to resolve texture due to upward reference: #stem in minecraft:block/pumpkin_stem_stage4
[18Feb2021 15:44:48.330] [Server-Worker-4/WARN] [net.minecraft.client.renderer.model.BlockModel/]: Unable to resolve texture due to upward reference: #stem in minecraft:block/melon_stem_stage3
[18Feb2021 15:44:48.330] [Server-Worker-4/WARN] [net.minecraft.client.renderer.model.BlockModel/]: Unable to resolve texture due to upward reference: #stem in minecraft:block/melon_stem_stage2
[18Feb2021 15:44:48.330] [Server-Worker-4/WARN] [net.minecraft.client.renderer.model.BlockModel/]: Unable to resolve texture due to upward reference: #stem in minecraft:block/melon_stem_stage5
[18Feb2021 15:44:48.330] [Server-Worker-4/WARN] [net.minecraft.client.renderer.model.BlockModel/]: Unable to resolve texture due to upward reference: #stem in minecraft:block/melon_stem_stage4
[18Feb2021 15:44:48.331] [Server-Worker-4/WARN] [net.minecraft.client.renderer.model.BlockModel/]: Unable to resolve texture due to upward reference: #stem in minecraft:block/melon_stem_stage1
[18Feb2021 15:44:48.331] [Server-Worker-4/WARN] [net.minecraft.client.renderer.model.BlockModel/]: Unable to resolve texture due to upward reference: #stem in minecraft:block/melon_stem_stage0
[18Feb2021 15:44:48.332] [Server-Worker-4/WARN] [net.minecraft.client.renderer.model.BlockModel/]: Unable to resolve texture due to upward reference: #stem in minecraft:block/melon_stem_stage7
[18Feb2021 15:44:48.332] [Server-Worker-4/WARN] [net.minecraft.client.renderer.model.BlockModel/]: Unable to resolve texture due to upward reference: #stem in minecraft:block/melon_stem_stage6
[18Feb2021 15:44:48.484] [Server-Worker-4/WARN] [net.minecraft.client.renderer.texture.AtlasTexture/]: Texture minecraft:block/melon_side_stage6 with size 4x4 limits mip level from 4 to 2
[18Feb2021 15:44:48.668] [Server-Worker-4/ERROR] [net.minecraftforge.fml.ModLoader/LOADING]: Skipping lifecycle event ENQUEUE_IMC, 1 errors found.
[18Feb2021 15:44:48.669] [Server-Worker-4/FATAL] [net.minecraftforge.fml.ModLoader/LOADING]: Failed to complete lifecycle event ENQUEUE_IMC, 1 errors found
[18Feb2021 15:44:48.669] [Server-Worker-4/FATAL] [net.minecraftforge.eventbus.EventBus/EVENTBUS]: EventBus 0 shutting down - future events will not be posted.
java.lang.Exception: stacktrace
	at net.minecraftforge.eventbus.EventBus.shutdown(EventBus.java:278) [eventbus-1.0.0-service.jar:?]
	at net.minecraftforge.fml.client.ClientModLoader.lambda$createRunnableWithCatch$5(ClientModLoader.java:115) [?:?]
	at net.minecraftforge.fml.client.ClientModLoader$$Lambda$2002/1338446903.run(Unknown Source) [?:?]
	at net.minecraftforge.fml.client.ClientModLoader.finishModLoading(ClientModLoader.java:136) [?:?]
	at net.minecraftforge.fml.client.ClientModLoader.lambda$onreload$4(ClientModLoader.java:107) [?:?]
	at net.minecraftforge.fml.client.ClientModLoader$$Lambda$2376/1218846264.run(Unknown Source) [?:?]
	at java.util.concurrent.CompletableFuture.uniRun(CompletableFuture.java:705) [?:1.8.0_51]
	at java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:687) [?:1.8.0_51]
	at java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:443) [?:1.8.0_51]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) [?:1.8.0_51]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) [?:1.8.0_51]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689) [?:1.8.0_51]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) [?:1.8.0_51]
[18Feb2021 15:44:48.822] [Client thread/INFO] [net.minecraft.client.audio.SoundSystem/]: OpenAL initialized.
[18Feb2021 15:44:48.823] [Client thread/INFO] [net.minecraft.client.audio.SoundEngine/SOUNDS]: Sound engine started
[18Feb2021 15:44:49.083] [Client thread/INFO] [net.minecraft.client.renderer.texture.AtlasTexture/]: Created: 1024x512 textures-atlas
[18Feb2021 15:44:49.550] [Client thread/WARN] [net.minecraft.client.renderer.model.BlockModel/]: Unable to resolve texture due to upward reference: #stem in minecraft:block/pumpkin_stem_stage0
[18Feb2021 15:44:49.650] [Client thread/WARN] [net.minecraft.client.renderer.model.BlockModel/]: Unable to resolve texture due to upward reference: #stem in minecraft:block/pumpkin_stem_stage5
[18Feb2021 15:44:49.650] [Client thread/WARN] [net.minecraft.client.renderer.model.BlockModel/]: Unable to resolve texture due to upward reference: #stem in minecraft:block/pumpkin_stem_stage6
[18Feb2021 15:44:49.651] [Client thread/WARN] [net.minecraft.client.renderer.model.BlockModel/]: Unable to resolve texture due to upward reference: #stem in minecraft:block/pumpkin_stem_stage7
[18Feb2021 15:44:49.651] [Client thread/WARN] [net.minecraft.client.renderer.model.BlockModel/]: Unable to resolve texture due to upward reference: #stem in minecraft:block/pumpkin_stem_stage1
[18Feb2021 15:44:49.651] [Client thread/WARN] [net.minecraft.client.renderer.model.BlockModel/]: Unable to resolve texture due to upward reference: #stem in minecraft:block/pumpkin_stem_stage2
[18Feb2021 15:44:49.652] [Client thread/WARN] [net.minecraft.client.renderer.model.BlockModel/]: Unable to resolve texture due to upward reference: #stem in minecraft:block/pumpkin_stem_stage3
[18Feb2021 15:44:49.652] [Client thread/WARN] [net.minecraft.client.renderer.model.BlockModel/]: Unable to resolve texture due to upward reference: #stem in minecraft:block/pumpkin_stem_stage4
[18Feb2021 15:44:49.775] [Client thread/WARN] [net.minecraft.client.renderer.model.BlockModel/]: Unable to resolve texture due to upward reference: #stem in minecraft:block/melon_stem_stage3
[18Feb2021 15:44:49.775] [Client thread/WARN] [net.minecraft.client.renderer.model.BlockModel/]: Unable to resolve texture due to upward reference: #stem in minecraft:block/melon_stem_stage2
[18Feb2021 15:44:49.776] [Client thread/WARN] [net.minecraft.client.renderer.model.BlockModel/]: Unable to resolve texture due to upward reference: #stem in minecraft:block/melon_stem_stage5
[18Feb2021 15:44:49.776] [Client thread/WARN] [net.minecraft.client.renderer.model.BlockModel/]: Unable to resolve texture due to upward reference: #stem in minecraft:block/melon_stem_stage4
[18Feb2021 15:44:49.776] [Client thread/WARN] [net.minecraft.client.renderer.model.BlockModel/]: Unable to resolve texture due to upward reference: #stem in minecraft:block/melon_stem_stage1
[18Feb2021 15:44:49.776] [Client thread/WARN] [net.minecraft.client.renderer.model.BlockModel/]: Unable to resolve texture due to upward reference: #stem in minecraft:block/melon_stem_stage0
[18Feb2021 15:44:49.776] [Client thread/WARN] [net.minecraft.client.renderer.model.BlockModel/]: Unable to resolve texture due to upward reference: #stem in minecraft:block/melon_stem_stage7
[18Feb2021 15:44:49.777] [Client thread/WARN] [net.minecraft.client.renderer.model.BlockModel/]: Unable to resolve texture due to upward reference: #stem in minecraft:block/melon_stem_stage6
[18Feb2021 15:44:49.962] [Client thread/INFO] [net.minecraft.client.renderer.texture.AtlasTexture/]: Created: 256x256 textures/particle-atlas
[18Feb2021 15:44:49.964] [Client thread/INFO] [net.minecraft.client.renderer.texture.AtlasTexture/]: Created: 256x256 textures/painting-atlas
[18Feb2021 15:44:49.965] [Client thread/INFO] [net.minecraft.client.renderer.texture.AtlasTexture/]: Created: 128x128 textures/mob_effect-atlas

**Comment by ochotonida** [comment]
Updating forge should fix the issue
